budget/urls.py
from django.urls import  path
from .views import IndexView, BudgetCreateView, BudgetUpdateView, BudgetDeleteView, PDFDowloadView, PricesListView, PricesUpdateView, PricesDeleteView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("budget/add/", BudgetCreateView.as_view(), name="add_budget"),
    path("budget/update/<int:pk>/", BudgetUpdateView.as_view(), name="update_budget"),
    path("budget/delete/<int:pk>/", BudgetDeleteView.as_view(), name="delete_budget"),
    path("budget/dowload/<int:pk>/", PDFDowloadView.as_view(), name="dowload_budget"),
    path("budget/prices/", PricesListView.as_view(), name="prices_list"),
    path("budget/prices/update/<int:pk>/", PricesUpdateView.as_view(), name="update_price"),
    path("budget/prices/delete/<int:pk>/", PricesDeleteView.as_view(), name="delete_price"),


]

quote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('', include("budget.urls")),
    
]

budget/models.py
from django.db import models
from accounts.models import Company
# Create your models here.

class Budget(models.Model):
    company = models.ForeignKey(Company, verbose_name="Compañia", on_delete=models.CASCADE)
    company_contact = models.CharField(verbose_name="Contacto", max_length=150)
    vehicles = models.IntegerField(verbose_name="Vehículos", null=True, blank=True, default=0)
    people = models.IntegerField(verbose_name="Personas", null=True, blank=True, default=0)
    trucks = models.IntegerField(verbose_name="Camiones", null=True, blank=True, default=0)
    containers = models.IntegerField(verbose_name="Camiones", null=True, blank=True, default=0)
    motorcycles = models.IntegerField(verbose_name="Camiones", null=True, blank=True, default=0)
    pets = models.IntegerField(verbose_name="Mascotas", null=True, blank=True, default=0)
    creator = models.ForeignKey("accounts.Profile", verbose_name="Autor", on_delete=models.CASCADE)
    quantity = models.SmallIntegerField(default=0)
    unit_cost = models.SmallIntegerField(default=0)
    total = models.IntegerField(verbose_name="Total", default=0)
    created_at = models.DateTimeField(verbose_name="Creación", auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="Modificación", auto_now=True, auto_now_add=False)
    foreing = models.BooleanField(verbose_name="Foraneo")
    
    def __str__(self):
        return self.company_contact
    
    
    class Meta:
        verbose_name = "Presupuesto"
        verbose_name_plural = "Presupuestos"

class Prices(models.Model):

    name = models.CharField(verbose_name="Rango", max_length=50)
    price = models.SmallIntegerField(default=0)
    value = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.name
    

budget/forms.py
from .models import Budget, Prices
from django import forms
#from accounts.models import Company

class BudgetModelForm(forms.ModelForm):
    
    company_contact = forms.CharField(required=True, label="Contacto", widget=forms.TextInput(
            attrs={'class': 'form-control',
            }
    ))


    vehicles = forms.IntegerField(label="Vehículos", initial=0, widget=forms.NumberInput(
        attrs={'class': 'form-control'}
    ))
    
    trucks = forms.IntegerField(label="Vehículos", initial=0, widget=forms.NumberInput(
        attrs={'class': 'form-control'}
    ))
    
    trucks = forms.IntegerField(label="Camiones", initial=0, widget=forms.NumberInput(
        attrs={'class': 'form-control'}
    ))
    
    people = forms.IntegerField(label="Personas", initial=0, widget=forms.NumberInput(
        attrs={'class': 'form-control'}
    ))
    
    pets = forms.IntegerField(label="Mascota", initial=0, widget=forms.NumberInput(
        attrs={'class': 'form-control'}
    ))
    
    containers = forms.IntegerField(label="Contenedores", initial=0, widget=forms.NumberInput(
        attrs={'class': 'form-control'}
    ))
    
    motorcycles  = forms.IntegerField(label="Motocicletas", initial=0, widget=forms.NumberInput(
        attrs={'class': 'form-control'}
    ))

    class Meta:
        model = Budget
        fields = ("company", "company_contact", "vehicles", "containers", "motorcycles", "trucks", "people", "pets", "foreing")


class PricesModelForm(forms.ModelForm):

    class Meta:
        model = Prices
        fields = ("name", "price")

budget/views.py
from django.shortcuts import render, redirect,reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Budget, Prices
from .forms import BudgetModelForm, PricesModelForm
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.http import JsonResponse, HttpResponse, FileResponse
from .utils import get_quantity, PDFHelper, delete_files
from django.conf import settings
from django.views.generic.list import ListView
#Create your views here.

class IndexView(LoginRequiredMixin, View):
    login_url = "/login/"
    
    def get(self, request, *args, **kwargs):
        budgets = Budget.objects.all().order_by("-created_at")
        form = BudgetModelForm()
        
        return render(request, 'budget/index.html', locals())


class BudgetCreateView(CreateView, LoginRequiredMixin):
    model = Budget
    template_name = 'budget/budget_form.html'
    success_url = reverse_lazy('index')
    form_class = BudgetModelForm
    

    def post(self, request, *args, **kwargs):
        quantity = 0
        form = BudgetModelForm(request.POST)

        
        if form.is_valid():
            quantity += int(request.POST.get("vehicles"))
            quantity += int(request.POST.get("trucks"))
            quantity += int(request.POST.get("pets"))
            quantity += int(request.POST.get("people"))
            quantity += int(request.POST.get("containers"))
            quantity += int(request.POST.get("motorcycles"))
            price, total = get_quantity(quantity)
            budget = Budget.objects.create(
                company=form.cleaned_data['company'],
                company_contact=form.cleaned_data["company_contact"],
                vehicles=form.cleaned_data["vehicles"],
                trucks=form.cleaned_data["trucks"],
                pets=form.cleaned_data["pets"],
                people=form.cleaned_data["people"],
                containers=form.cleaned_data["containers"],
                motorcycles=form.cleaned_data["motorcycles"],
                foreing=form.cleaned_data["foreing"],
                creator=request.user.profile,
                quantity=quantity,
                unit_cost=price,
                total=total
            )
            json3 = {'pk': budget.pk}

        return JsonResponse(json3, safe=False)


class BudgetUpdateView(UpdateView, LoginRequiredMixin):
    model = Budget
    template_name = 'budget/update_budget.html'
    success_url = reverse_lazy('index')
    form_class = BudgetModelForm


    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        quantity = 0
        json3 = {}
        try:
            self.object = self.get_object()
            form = BudgetModelForm(request.POST, instance=self.object)
            if form.is_valid():
                
                budget_upd = form.save(commit=False)
                
                quantity += int(request.POST.get("vehicles"))
                quantity += int(request.POST.get("trucks"))
                quantity += int(request.POST.get("pets"))
                quantity += int(request.POST.get("people"))
                quantity += int(request.POST.get("containers"))
                quantity += int(request.POST.get("motorcycles"))
                price, total = get_quantity(quantity)

                budget_upd.quantity=quantity
                budget_upd.unit_cost=price
                budget_upd.creator=request.user.profile
                budget_upd.total=total

                budget_upd.save()
            
                json3 = {"pk":budget_upd.pk}

        except  Exception as e:
            json3 = {"error":"KO"}
        return JsonResponse(json3, safe=False)


class BudgetDeleteView(DeleteView, LoginRequiredMixin):
    model = Budget
    template_name = 'budget/delete_budget.html'
    success_url = reverse_lazy('index')


class PDFDowloadView(View, LoginRequiredMixin):

    def get(self, request, *args, **kwargs):
        try:
            budget = Budget.objects.get(id=self.kwargs.get("pk"))
            PDFHelper.create_pdf_budget(budget)
            file = open(str(settings.BASE_DIR)+"/budget/Cotizacion_.pdf", 'rb')
            response = FileResponse(file)
            delete_files(budget)
            return response
        except  Exception as e:
            print(e)


class PricesListView(ListView, LoginRequiredMixin):
    model = Prices


class PricesDeleteView(DeleteView, LoginRequiredMixin):
    model = Prices
    template_name = 'budget/delete_price.html'
    success_url = reverse_lazy('prices_list')
    form_class = PricesModelForm


class PricesUpdateView(UpdateView, LoginRequiredMixin):
    model = Prices
    template_name = 'budget/update_price.html'
    success_url = reverse_lazy('prices_list')
    form_class = PricesModelForm

    def post(self, request, *args, **kwargs):
        json3 = {}
        form = PricesModelForm(request.POST or None)
        if form.is_valid():
            price_upd = form.save(commit=False)
            price = form.cleaned_data.get("price")
            price_upd.price = price
            price_upd.save()
            json3 = {"pk":price_upd.pk}
        return JsonResponse(json3, safe=False)

templates/budget/budget_form.html
{% extends 'base.html' %}
{% block title %}Globspot | Nueva Cotización{% endblock %}


  {% block content %} 
  <div class="container">
    <form id="budget_form" method="post" action="{% url 'add_budget' %}" accept-charset="utf-8">
            {% csrf_token %}
            <fieldset>
              <legend>Cliente</legend>
              
              <div class="form-group col-12">
                <label for="{{form.company.id_for_label}}">{{form.company.label}}: </label>
                {{form.company}}
              </div>
              <div class="form-group col-12">
                <label for="{{form.company_contact.id_for_label}}">{{form.company_contact.label}}: </label>
                {{form.company_contact}}
              </div>
            </fieldset>
            <fieldset>
              <legend>Cantidad</legend>
              <div class="d-flex">
              <div class="form-group col-6">
                <label for="{{form.vehicles.id_for_label}}">{{form.vehicles.label}}: </label>
                {{form.vehicles}}
              </div>
              <div class="form-group col-6">
                <label for="{{form.trucks.id_for_label}}">{{form.trucks.label}}: </label>
                {{form.trucks}}
              </div>
            </div>

            <div class="d-flex">
              <div class="form-group col-6">
                <label for="{{form.people.id_for_label}}">{{form.people.label}}: </label>
                {{form.people}}
              </div>
              <div class="form-group col-6">
                <label for="{{form.pets.id_for_label}}">{{form.pets.label}}: </label>
                {{form.pets}}
              </div>
            </div>

            <div class="d-flex">
              <div class="form-group col-6">
                <label for="{{form.containers.id_for_label}}">{{form.containers.label}}: </label>
                {{form.containers}}
              </div>
              <div class="form-group col-6">
                <label for="{{form.motorcycles.id_for_label}}">{{form.motorcycles.label}}: </label>
                {{form.motorcycles}}
              </div>
            </div>
            <hr>
            <div class="form-group col-12">
                <label for="{{form.foreing.id_for_label}}">{{form.foreing.label}}: </label>
                {{form.foreing}}
              </div>
            </div>

            </fieldset>
          <div id="files"></div>
        </div>
        <div class="modal-footer" >
          <a href="{% url 'index' %}" class="btn btn-danger" >Cancelar</a>
          <input type="submit" class="btn btn-primary" value="Guardar">
        </div>
      </form>
    </div>
</body>
{% endblock %}

{% block js %}
 
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script type="text/javascript">

  $('#id_company').select2({ width: '100%' });

  $("#id_company").on("change", function(e){
    console.log("Cambio")
    id_comp = $("#id_company").val()
    $.ajax({
      type:"GET",
      url :"{% url 'get_contact_company' %}?comp_id="+id_comp,
      success: function(xhr, ajaxOptions, thrownError){
        $("#id_company_contact").val(xhr.executive)
      }
    })
  }
    )
  
  $("#budget_form").on('submit', function(e){
    e.preventDefault();
    data = $('form').serialize()
    $.ajax({
      type:"POST",
      url: "{% url 'add_budget' %}",
      data:data,
      success: function (xhr, ajaxOptions, thrownError) {
        if (xhr.pk){
          url_dowload = "budget/dowload/"+xhr.pk+"/"
          myhtml = `<a href="${url_dowload}" >Prueba</a>`,
          Swal.fire({
            html: `<h1>¡Guardada!</h1>
            <p>Cotización Guardada.</p>
            <br>
            <a href=/budget/dowload/${xhr.pk}/ target="_blank">Ver cotización</a>
            `,
            icon: "success",
          })
            .then(function (result) {
              if (result.isConfirmed) {
                  window.location = "{% url 'index' %}";
              }
          })

          
          
        }else{
          Swal.fire({
            icon: 'error',
            title: 'Oops...',
            text: '¡Intentelo más tarde!'
          })
        }
      },      
      error: function (xhr, ajaxOptions, thrownError) {
        
      }

      })

    })


</script>
{% endblock %}

templates/budget/delete_budget.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 
Eliminar {{object.company}}
{%endblock%}

{% block content %}
<div class="container">
    <div>
        <h2>¿Deseas eliminar la cotización de {{object.company}}?</h2>
        <form method="post" action="{% url 'delete_budget' object.pk %}">
            {% csrf_token %} 
            <input class="btn btn-danger" type="submit" value="Si, Eliminar">
            <a href="{% url 'index' %}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
    

</div>
{% endblock %}

templates/budget/delete_price.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 
Globspot | Eliminar {{object.company}}
{%endblock%}

{% block content %}
<div class="container">
    <div>
        <h2>¿Deseas eliminar el precio de {{object.name}}?</h2>
        <form method="post" action="{% url 'delete_budget' object.pk %}">
            {% csrf_token %} 
            <input class="btn btn-danger" type="submit" value="Si, Eliminar">
            <a href="{% url 'prices_list' %}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
    

</div>
{% endblock %}

templates/budget/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Globspot | Cotizador{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
<link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
<script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
{% endblock %}

{% block content %}

<div class="content-wrapper">
<div class="container">
<h1 class="pt-1"><i class="fas fa-file-alt"></i> Cotizaciones</h1>
  <div class="card mt-5">
  <div class="card-header">
    <a  class="btn btn-primary" href="{% url 'add_budget' %}">
      <i class="fas fa-plus"></i> Nuevo
    </a>
  </div>
  <div class="card-body">
      <table id="data" class="table table-bordered table-hover dataTable dtr-inline">
        <thead>
          <tr>
            <th scope="col">Compañia</th>
            <th scope="col">Contacto</th>
            <th scope="col">Precio por Unidad</th>
            <th scope="col">Cantidad</th>
            <th scope="col">Total</th>
            <th scope="col">Fecha</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody>
            {% for budget in budgets%}
          <tr>
            <td>{{budget.company}}</td>
            <td>{{budget.company_contact}}</td>
            <td>{{budget.unit_cost|intcomma}}</td>
            <td>{{budget.quantity}}</td>
            <td>{{budget.total|intcomma}}</td>
            <td>{{budget.created_at}}</td>
            <td class="text-center">
                <a href="{% url 'dowload_budget' budget.pk %}" target="_blank" data-bs-toggle="Descargar" data-bs-placement="top" title="Descargar"><i class="fas fa-cloud-download-alt"></i></a>
                <a href="{% url 'update_budget' budget.pk %}"  data-toggle="tooltip" data-bs-placement="top" title="Actualizar"><i class="fas fa-pen" style="color:#F0AD4E;"></i></a>
                <a href="{% url 'delete_budget' budget.pk %}"  data-toggle="tooltip" data-bs-placement="top" title="Eliminar"><i class="fas fa-trash-alt" style="color:red;"></i></a>
                
            </td>
          </tr>
          {% endfor %}
        </tbody>
        
      </table>
  </div>
  </div>
</div>
</div>
{% endblock %}

{% block js %}

<script type="text/javascript">
  var table1 = $('#data');
  
    $('#data').DataTable({
        responsive: true,
        autoWidth: false
    });

    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })

</script>
{% endblock %}

templates/budget/prices_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block title %}Globspot | Precios{% endblock %}


{% block content %}
<div class="content-wrapper">
    <div class="container">
    <h1 class="pt-1"><i class="fas fa-file-invoice-dollar"></i> Precios</h1>
      <div class="card mt-3">
      <div class="card-header">
              </div>
      <div class="card-body">
          <table id="data" class="table table-bordered table-hover dataTable dtr-inline">
            <thead>
              <tr>
                <th scope="col">Cantidad</th>
                <th scope="col">Precio</th>
                <th scope="col">Acciones</th>
              </tr>
            </thead>
            <tbody>
                {% for price in object_list %}
              <tr>
                <td>{{price.name}}</td>
                <td>{{price.price|intcomma}}</td>
                <td class="text-center">
                    <a href="{% url 'update_price' price.pk %}"  data-toggle="tooltip" data-bs-placement="top" title="Actualizar"><i class="fas fa-pen" style="color:#F0AD4E;"></i></a>
                    <a href="{% url 'delete_price' price.pk %}"  data-toggle="tooltip" data-bs-placement="top" title="Eliminar"><i class="fas fa-trash-alt" style="color:red;"></i></a>
                    
                </td>
              </tr>
              {% endfor %}
            </tbody>
            
          </table>
      </div>
      </div>
    </div>
    </div>
{% endblock %}

templates/budget/update_budget.html
{% extends 'base.html' %}
{% block title %}Globspot | Modificar Cotización{% endblock %}


  {% block content %} 
  <div class="container">
    <form id="update_budget_form" method="post" action="{% url 'update_budget' object.pk %}" accept-charset="utf-8">
            {% csrf_token %}
            <fieldset>
              <legend>Cliente</legend>
              
              <div class="form-group col-12">
                <label for="{{form.company.id_for_label}}">{{form.company.label}}: </label>
                {{form.company}}
              </div>
              <div class="form-group col-12">
                <label for="{{form.company_contact.id_for_label}}">{{form.company_contact.label}}: </label>
                {{form.company_contact}}
              </div>
            </fieldset>
            <fieldset>
              <legend>Cantidad</legend>
              <div class="d-flex">
              <div class="form-group col-6">
                <label for="{{form.vehicles.id_for_label}}">{{form.vehicles.label}}: </label>
                {{form.vehicles}}
              </div>
              <div class="form-group col-6">
                <label for="{{form.trucks.id_for_label}}">{{form.trucks.label}}: </label>
                {{form.trucks}}
              </div>
            </div>

            <div class="d-flex">
              <div class="form-group col-6">
                <label for="{{form.people.id_for_label}}">{{form.people.label}}: </label>
                {{form.people}}
              </div>
              <div class="form-group col-6">
                <label for="{{form.pets.id_for_label}}">{{form.pets.label}}: </label>
                {{form.pets}}
              </div>
            </div>

            <div class="d-flex">
              <div class="form-group col-6">
                <label for="{{form.containers.id_for_label}}">{{form.containers.label}}: </label>
                {{form.containers}}
              </div>
              <div class="form-group col-6">
                <label for="{{form.motorcycles.id_for_label}}">{{form.motorcycles.label}}: </label>
                {{form.motorcycles}}
              </div>
            </div>
            <div class="form-group col-12">
                <label for="{{form.foreing.id_for_label}}">{{form.foreing.label}}: </label>
                {{form.foreing}}
              </div>
            </div>

            </fieldset>
          <div id="files"></div>
        </div>
        <div class="modal-footer" style="background-color: #F7F7F9;">
          <a href="{% url 'index' %}" class="btn btn-danger" >Cancelar</a>
          <input type="submit" class="btn btn-primary" value="Guardar">
        </div>
      </form>
    </div>
</body>
{% endblock %}

{% block js %}
 
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script type="text/javascript">

  $('#id_company').select2({ width: '100%' });


  $("#id_company").on("change", function(e){
    console.log("Cambio")
    id_comp = $("#id_company").val()
    $.ajax({
      type:"GET",
      url :"{% url 'get_contact_company' %}?comp_id="+id_comp,
      success: function(xhr, ajaxOptions, thrownError){
        $("#id_company_contact").val(xhr.executive)
      }
    })
  }
    )

  $("#update_budget_form").on('submit', function(e){
    e.preventDefault();
    data = $('form').serialize()
    $.ajax({
      type:"POST",
      url: "{% url 'update_budget' object.pk %}",
      data:data,
      success: function (xhr, ajaxOptions, thrownError) {
        if (xhr.pk){
            Swal.fire({
              title: "¡Actualizado!",
              html: "<a href={% url 'dowload_budget' object.pk %} target=_blank> Ver Cotización</a>",
              icon: "success",
              buttons: true,
              dangerMode: true,
             }
          )
          .then(function (result) {
            console.log(result)
            if (result.isConfirmed) {
                window.location = "{% url 'index' %}";
            }
        })

        }
      },      
      error: function (xhr, ajaxOptions, thrownError) {
        
      }
      
    })
      
    })
    




    $("#budget_form").on('submit', function(e){
      e.preventDefault();
      data = $('form').serialize()
      $.ajax({
        type:"POST",
        url: "{% url 'add_budget' %}",
        data:data,
        success: function (xhr, ajaxOptions, thrownError) {
          console.log(xhr)
          if (xhr.pk){
              Swal.fire({
            title:'¡Guardado',
            type:'success',
            text:'Se ha creado la cotización.'
              }) 
              .then(function (result) {
                console.log(result)
                if (result.isConfirmed) {
                    window.location = "{% url 'index' %}";
                }
            })
  
            
            
          }else{
            Swal.fire({
              icon: 'error',
              title: 'Oops...',
              text: '¡Intentelo más tarde!'
            })
          }
        },      
        error: function (xhr, ajaxOptions, thrownError) {
          
        }
  
        })
  
      })

</script>
{% endblock %}

templates/budget/update_price.html
{% extends 'base.html' %}
{% block title %}Globspot | Actualizar Precio{% endblock %}


  {% block content %} 
  <div class="container">
    <form id="update_price_form" method="post" action="{% url 'update_price' object.pk %}" accept-charset="utf-8">
      {% csrf_token %}
        <div class="col-12">
            <fieldset>
                <legend>Precio</legend>
                
                <div class="form-group col-12">
                  <label for="{{form.name.id_for_label}}">{{form.name.label}}: </label>
                  {{form.name}}
                </div>
                <div class="form-group col-12">
                  <label for="{{form.description.id_for_label}}">{{form.price.label}}: </label>
                  {{form.price}}
                </div>
              </fieldset>
        </div>
        <div class="modal-footer">
            <input type="submit" value="Guardar" class="btn btn-success">
            <a href="{% url 'prices_list' %}" class="btn btn-danger" >Cancelar</a>

        </div>
    </form>

</div>

{% endblock %}

{% block js %}
 
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script type="text/javascript">

  $('#id_company').select2({ width: '100%' });

    
    $("#update_price_form").on('submit', function(e){
      e.preventDefault();
      data = $('form').serialize()
      $.ajax({
        type:"POST",
        url: "{% url 'update_price' object.pk  %}",
        data:data,
        success: function (xhr, ajaxOptions, thrownError) {
          console.log(xhr)
          if (xhr.pk){
              Swal.fire(
            '¡Guardado!',
            'Se ha actualizado el precio.'
              ) 
              .then(function (result) {
                console.log(result)
                if (result.isConfirmed) {
                    window.location = "{% url 'prices_list' %}";
                }
            })
  
            
            
          }else{
            Swal.fire({
              icon: 'error',
              title: 'Oops...',
              text: '¡Intentelo más tarde!'
            })
          }
        },      
        error: function (xhr, ajaxOptions, thrownError) {
          
        }

        })

      })

    

</script>
{% endblock %}